"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import field_mask_pb2 as _field_mask_pb2
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import typing as _typing
from typing import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class WhereIsOneRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MASK_FIELD_NUMBER: _builtins.int
    SWHID_FIELD_NUMBER: _builtins.int
    swhid: _builtins.str
    """Core SWHID of the node to lookup"""
    @_builtins.property
    def mask(self) -> _field_mask_pb2.FieldMask:
        """FieldMask of which fields are to be returned (e.g., "swhid,anchor,origin").
        By default, all fields are returned.
        """

    def __init__(
        self,
        *,
        mask: _field_mask_pb2.FieldMask | None = ...,
        swhid: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_mask", b"_mask", "mask", b"mask"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_mask", b"_mask", "mask", b"mask", "swhid", b"swhid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__mask: _TypeAlias = _typing.Literal["mask"]  # noqa: Y015
    _WhichOneofArgType__mask: _TypeAlias = _typing.Literal["_mask", b"_mask"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__mask) -> _WhichOneofReturnType__mask | None: ...

Global___WhereIsOneRequest: _TypeAlias = WhereIsOneRequest  # noqa: Y015

@_typing.final
class WhereAreOneRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MASK_FIELD_NUMBER: _builtins.int
    SWHID_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def mask(self) -> _field_mask_pb2.FieldMask:
        """FieldMask of which fields are to be returned (e.g., "swhid,anchor,origin").
        By default, all fields are returned.
        """

    @_builtins.property
    def swhid(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Core SWHIDs of the nodes to lookup"""

    def __init__(
        self,
        *,
        mask: _field_mask_pb2.FieldMask | None = ...,
        swhid: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_mask", b"_mask", "mask", b"mask"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_mask", b"_mask", "mask", b"mask", "swhid", b"swhid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__mask: _TypeAlias = _typing.Literal["mask"]  # noqa: Y015
    _WhichOneofArgType__mask: _TypeAlias = _typing.Literal["_mask", b"_mask"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__mask) -> _WhichOneofReturnType__mask | None: ...

Global___WhereAreOneRequest: _TypeAlias = WhereAreOneRequest  # noqa: Y015

@_typing.final
class WhereIsOneResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SWHID_FIELD_NUMBER: _builtins.int
    ANCHOR_FIELD_NUMBER: _builtins.int
    ORIGIN_FIELD_NUMBER: _builtins.int
    swhid: _builtins.str
    """Core SWHID of the node whose lookup was requested"""
    anchor: _builtins.str
    """Core SWHID of a revision or release that contains the above node"""
    origin: _builtins.str
    """URL of an origin that contains the anchor"""
    def __init__(
        self,
        *,
        swhid: _builtins.str = ...,
        anchor: _builtins.str | None = ...,
        origin: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_anchor", b"_anchor", "_origin", b"_origin", "anchor", b"anchor", "origin", b"origin"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_anchor", b"_anchor", "_origin", b"_origin", "anchor", b"anchor", "origin", b"origin", "swhid", b"swhid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__anchor: _TypeAlias = _typing.Literal["anchor"]  # noqa: Y015
    _WhichOneofArgType__anchor: _TypeAlias = _typing.Literal["_anchor", b"_anchor"]  # noqa: Y015
    _WhichOneofReturnType__origin: _TypeAlias = _typing.Literal["origin"]  # noqa: Y015
    _WhichOneofArgType__origin: _TypeAlias = _typing.Literal["_origin", b"_origin"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__anchor) -> _WhichOneofReturnType__anchor | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__origin) -> _WhichOneofReturnType__origin | None: ...

Global___WhereIsOneResult: _TypeAlias = WhereIsOneResult  # noqa: Y015
