provenance:
    storage:
        cls: rabbitmq  # client configuration
        url: amqp://rabbitmq:5672/%2f
        storage_config:
            cls: postgresql
            db:
                host: storage-db
                dbname: provenance
                user: provenance
                password: provenancepassword
        batch_size: 10000
        prefetch_count: 100
        wait_min: 60
        wait_per_batch: 60


    archive:
        cls: multiplexer
        archives:
            - cls: graph
              url: http://graph.internal.softwareheritage.org:5009/graph
              storage:
                  cls: remote
                  url: http://webapp1.internal.softwareheritage.org:5002
            - cls: api
              storage:
                  cls: remote
                  url: http://webapp1.internal.softwareheritage.org:5002
        # cls: direct
        # db: 
        #     host: swh-storage-db
        #     port: 5432
        #     dbname: swh
        #     user: guest
        # cls: api

    org_server:  # origin provider
        host: origin_server
        port: 5555
        batch_size: 1
